// backend/services/pdfService.js

const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");

/**
 * 🧠 NEXA EXECUTIVE PDF REPORT ENGINE
 * Generates structured safety intelligence reports
 */
const generateExecutivePDF = (data = {}) => {
  const {
    executiveReport = {},
    predictions = [],
    humanProfiles = [],
    psychProfiles = [],
    complianceReport = {},
  } = data;

  const filePath = path.join(
    __dirname,
    "..",
    "reports",
    `nexa-report-${Date.now()}.pdf`
  );

  // Ensure directory exists
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const doc = new PDFDocument({ margin: 40 });

  doc.pipe(fs.createWriteStream(filePath));

  // =========================
  // TITLE PAGE
  // =========================
  doc.fontSize(20).text("NEXA SAFETY INTELLIGENCE REPORT", {
    align: "center",
  });

  doc.moveDown();
  doc.fontSize(12).text(`Generated: ${new Date().toISOString()}`, {
    align: "center",
  });

  doc.moveDown(2);

  // =========================
  // EXECUTIVE SUMMARY
  // =========================
  doc.fontSize(16).text("1. Executive Summary");
  doc.moveDown();

  doc.fontSize(11).text(
    executiveReport.summary ||
      "AI-generated aviation safety intelligence report."
  );

  doc.moveDown(2);

  // =========================
  // RISK ANALYSIS
  // =========================
  doc.fontSize(16).text("2. Risk Analysis");
  doc.moveDown();

  predictions.slice(0, 10).forEach((p, i) => {
    doc.fontSize(11).text(
      `${i + 1}. Flight ${p.flight || "N/A"} | Risk: ${p.risk || "N/A"} | Score: ${p.score || 0}`
    );
  });

  doc.moveDown(2);

  // =========================
  // HUMAN FACTORS
  // =========================
  doc.fontSize(16).text("3. Human Factors (Psychological Safety)");
  doc.moveDown();

  psychProfiles.slice(0, 10).forEach((p, i) => {
    doc.fontSize(11).text(
      `${i + 1}. Flight ${p.flight} | MRS: ${p.mentalReadiness} | PSI: ${p.psychSafety}`
    );
  });

  doc.moveDown(2);

  // =========================
  // COMPLIANCE
  // =========================
  doc.fontSize(16).text("4. Compliance Overview");
  doc.moveDown();

  doc.fontSize(11).text(
    complianceReport.summary ||
      "No compliance anomalies detected in current dataset."
  );

  doc.moveDown(2);

  // =========================
  // FOOTER
  // =========================
  doc.fontSize(10).text(
    "Generated by NEXA OS – AI Safety Intelligence Platform",
    { align: "center" }
  );

  doc.end();

  return filePath;
};

module.exports = { generateExecutivePDF };